### ISSUE TITLE
Description of types in docs/dev/macros.md confusing

### ISSUE THREAD

**Issue by driusan** [ircmaxell/php-compiler#13]
The documentation says:

> Second, the types are directly pulled from LLVM, and most single-token types are supported (including pointers).

However, the examples seem to be more like C style types (int64, int32, etc (which I guess is more like Go types, since C types would have _t at the end...)) than LLVM types which according to the (LLVM documentation)[https://llvm.org/docs/LangRef.html#integer-type] are formatted like "i64", "i32", "u8")

**Comment by ircmaxell** [comment]
Added https://github.com/ircmaxell/php-compiler/blob/master/docs/dev/types.md to attempt to start clarifying. Feel free to re-open if you think it's still confusing or if any changes are warranted.
