### ISSUE TITLE
How is it working?

### ISSUE THREAD

**Issue by acuna-public** [ircmaxell/php-compiler#75]
Thanks for this project and another ones too, it all awesome! But can I ask you how is it compiler works, for example which engine is it using for generate a native code, etc, because I don't believe that PHP have its own engine to generate a native code, so it needs a enterpreteur for working, and I don't see any nikic's PHP-Perser and even token_get_all for parsing the code in its source code. Thanks.

**Comment by maxymajzr** [comment]
@acuna-public the readme answers your question, first paragraph. Have you read it?

It mentions FFI, which stands for Foreign Functions Interface. It's a PHP 7.4 feature. Use GitHub's search and type `FFI::`, it'll list the bits of code you're after. Then, you can see what it hooks into and how the magic is done.

No language needs an enterpreneur, believe me.

**Comment by acuna-public** [comment]
@maxymajzr thanks, but no, FFI only allows to execute a C functions, not assembly PHP, I can't see the relation with FFI and proccessor bytecode, only to convert the PHP code to C code and compile it, but it's not a compilation, it's simply convertation, so it must called a PHP to C converter, not PHP compiler.

**Comment by ircmaxell** [comment]
It uses LLVM under the hood for the actual native compilation. So this compiler compiles from PHP into an intermediary representation, then into LLVM IR, then finally machine code, with the final step happening in LLVM itself.

**Comment by acuna-public** [comment]
Ah, thanks, it's finally answer my question at last, it made sense to wait a month for it...

**Comment by PurHur** [comment]
Here is an example how that looks like "in php" https://github.com/PurHur/php-compiler/blob/master/ext/standard/JitDate.php#L41
